name: Build

on:
  push:
    branches:
      - master
      - develop

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Run npm install
        run: npm install
      - name: Run npm ci
        run: npm ci
      - name: Build module
        run: npm run build
      - name: Run all tests
        run: npm run test:coverage
      - name: Upload Test reports to codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
