name: Publish to npm

on:
  release:
    types:
      - published

jobs:
  Bulid_Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Set global git username
        run: git config --global user.name "Javed Hussain"
      - name: Set global git useremail
        run: git config --global user.email "javedh-dev@hmail.com"
      - name: Set module version as release tag
        run: npm version ${{ github.event.release.tag_name }}

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
  
      - name: Run npm install
        run: npm install
      - name: Run npm ci
        run: npm ci
      - name: Build module
        run: npm run build
      - name: Run all tests
        run: npm test
      - name: Publish module to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Update version in package.json
        run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
